; This file was automatically generated by ScriptHubImporter.py
<<<<<<< Updated upstream
global g_ImportsGameVersion64 := 526
=======
global g_ImportsGameVersion64 := 522
>>>>>>> Stashed changes
global g_ImportsGameVersionPostFix64 := ""